app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('riple.urls')),
    path('',include('django.contrib.auth.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

riple/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save,post_delete
from .validators import validate_file_extension
import os
from django.core.exceptions import ValidationError
# Create your models here.
    
class Friends(models.Model):
    followers = models.ManyToManyField(User,related_name='followers',blank=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s friends list"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic=models.ImageField(null=False,blank=True,default="files/defaultdp.jpg")
    age=models.IntegerField(null=True,blank=True,default=18)
    name=models.CharField(null=True,blank=True,default="",max_length=30)
    bio=models.CharField(null=True,blank=True,default="",max_length=200)
    is_private=models.BooleanField(default=True,null=True,blank=True)
    def following(self):
        return Friends.objects.filter(followers=self.user)
    def followers(self):
        return self.user.friends.followers.all()
    @property
    def following_count(self):
        return self.following().count()
    @property
    def followers_count(self):
        return self.followers().count()

    def __str__(self):
        return self.user.username
    @property
    def display_bio(self):
        if self.bio != "":
            return self.bio[0:20]+'...'
        else:
            return ""

def create_profile(sender,instance,created,**kwargs):
    if created:
        profile=Profile.objects.create(user=instance)

post_save.connect(create_profile,sender=User)

def create_friends(sender,instance,created,**kwargs):
    if created:
        friends=Friends.objects.create(user=instance)

post_save.connect(create_friends,sender=User)

class Post(models.Model):
    caption = models.CharField(max_length=500,null=True,blank=True)
    pic = models.FileField(null=True,blank=True,upload_to="files/" , validators=[validate_file_extension]) #or video
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    time = models.DateTimeField(null=True,blank=True,auto_now_add=True)
    isavideo = models.BooleanField(null=True,blank=True)
    @property
    def display_date(self):
        return self.time.strftime("%b %d")
    @property
    def display_time(self):
        return self.time.strftime("%I:%M %p")
    @property
    def no_likes(self):
        return Like.objects.filter(post=self).count()
    def no_comments(self):
        return Comment.objects.filter(post=self).count()
    @property
    def likes(self):
        #all_users_who_liked
        user_list=[]
        for l in Like.objects.filter(post=self):
            user_list.append(l.user)
        return user_list
    @property
    def comments(self):
        #all_users_who_commented
        user_list=[]
        for c in Comment.objects.filter(post=self):
            user_list.append(c.user)
        return user_list
        
def setisavideo(sender,instance,created,**kwargs):
    if created:
        value = instance.pic
        ext = os.path.splitext(value.name)[1]
        video_exts = ['.mp4','.mov']
        if ext in video_exts:
            instance.isavideo=True
        else:
            instance.isavideo=False
        instance.save()

post_save.connect(setisavideo,sender=Post)

class Notification(models.Model):
    NOTIFICATION_TYPES=((1,'Like'),(2,'Comment'),(3,'Follow'),(4,'Request'),(5,'Aceepted'))
    post = models.ForeignKey(Post,null=True,blank=True,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="noti_from_user")
    notifier = models.ForeignKey(User,on_delete=models.CASCADE,related_name="noti_to_user")
    pic = models.ImageField(null=True,blank=True)
    is_seen = models.BooleanField(default=False)
    time = models.DateTimeField(null=True,blank=True,auto_now_add=True)
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)

    @property
    def notification_message(self):
        if self.notification_type==1:
            return "liked your post"
        elif self.notification_type==2:
            return "commented on your post"
        elif self.notification_type==3:
            return "followed you"
        elif self.notification_type==4:
            return "requested to follow you"
        else:
            return "accepted your request"
    
    @property
    def display_date(self):
        return self.time.strftime("%b %d")
    @property
    def display_time(self):
        return self.time.strftime("%I:%M %p")

class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE) #liker
    time=models.DateTimeField(null=True,blank=True,auto_now_add=True)
    def user_liked_post(sender,instance,*args, **kwargs):
        like=instance
        post=like.post
        liker=like.user
        user=post.user
        time=like.time
        pic=post.pic
        notify=Notification(post=post,user=user,notifier=liker,pic=pic,time=time,notification_type=1)
        notify.save() #this is not the save dictating the post_save signal

    def user_unliked_post(sender,instance,*args, **kwargs):
        unlike=instance
        post=unlike.post
        unliker=unlike.user
        user=post.user
        Notification.objects.filter(post=post,user=user,notifier=unliker,notification_type=1).delete()

post_save.connect(Like.user_liked_post,sender=Like)
post_delete.connect(Like.user_unliked_post,sender=Like)

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE) #commenter
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=1000,blank=False,null=False)


    @property
    def display_date(self):
        return self.time.strftime("%b %d")
    @property
    def display_time(self):
        return self.time.strftime("%I:%M %p")
    

    def comment_added(sender,instance,created,*args, **kwargs):
        if created:
            comment=instance
            post=comment.post
            commenter=comment.user
            user=post.user
            time=comment.time
            pic=post.pic
            notify=Notification(post=post,user=user,notifier=commenter,pic=pic,time=time,notification_type=2)
            notify.save()

    def comment_deleted(sender,instance,*args, **kwargs):
        comment=instance
        post=comment.post
        commenter=comment.user
        user=post.user
        Notification.objects.filter(post=post,user=user,notifier=commenter,notification_type=2).delete()

post_save.connect(Comment.comment_added,sender=Comment)
post_delete.connect(Comment.comment_deleted,sender=Comment)

class FeedPost(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ForeignKey(User,null=True,blank=True,related_name='post_followers',on_delete=models.CASCADE)
    users=models.ManyToManyField(User) #followers of the poster
    time=models.DateTimeField(null=False,blank=False)

    def is_user(self):
        is_user=False
        if self.user==user:
            is_user=True
        return is_user

def add_to_feed(sender,instance,created,*args, **kwargs):
    if created:
        users=Friends.objects.get(user=instance.user).followers.all()
        feed=FeedPost.objects.create(post=instance,time=instance.time)
        feed.save()
        for user in users:
            feed.users.add(user)
        feed.save()

post_save.connect(add_to_feed,sender=Post)

templates/app/followers.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/home2.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile2.css' %}">


<style>
    .following-container {
        width: 100vmin;
        min-height: 100vh;
        display: flex;
        justify-content: center;
        padding-left: 5%;
        padding-right: 5%;
        padding-top: 5vmin;
    }

    .outer-container {
        width: 100%;
        min-height: 100vh;
        display: flex;
        justify-content: center;
        background-color: rgb(238, 238, 238);
    }

    .followbtn {
        background-color: crimson;
        color: white;
        border: 0px;
        border-radius: 5px;
        width: fit-content;
        padding: 5px 10px 5px 10px;
        transition: 0.2s ease;
    }

    .followbtn:hover {
        background-color: rgb(173, 6, 39);
    }
</style>

<nav class="navbar navbar-expand-lg nav-color sticky" style="position: sticky;top: 0;z-index: 1;">
    <div class="container-fluid">
        <a class="navbar-brand" href="/user/{{user.username}}">
            <img class="home-self-img" src="{{user.profile.profile_pic.url}}">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-icons white" style="font-size: 40px;">list</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                        Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">
                        Profile</a>
                </li>
                <a class="nav-link active" aria-current="page" href="/notifications">
                    Notifications</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Requests
                    </a>
                    <ul class="dropdown-menu nav-color" aria-labelledby="navbarDropdown">
                        {% if follow_req_notifications %}
                        {% for n in follow_req_notifications %}
                        <li class="dropdown-item" style="background-color: black;">
                            <a href="/user/{{n.notifier.username}}">{{n.notifier.username}} requested to follow you</a>
                            <a href="/req_accept/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-light bg-light btn-sm">Accept</button></a>
                            <a href="/req_delete/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-danger btn-sm">Delete</button></a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li><a class="dropdown-item" href="#">No requests</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li>
                    <a class="nav-link active" aria-current="page" href="/post">
                        New Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>

            </ul>
            <form class="d-flex" action="/home_search" method="POST">
                {% csrf_token %}
                {% for msg in messages %}
                <p style="color: white;">{{msg}}</p>
                {% endfor %}
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-light bg-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<nav class="nav-color nav-footer">
    <a href="/"><i class="bi bi-house-door house-icon"></i></a>
</nav>

<div class="outer-container">
    <div class="following-container">
        {% if followers_list %}
        <ul class="list-group followcontainer" id="followinglist">
            {% for f in followers_list %}
            <li class="list-group-item center li-body">
                <div class="toast-header notibody">
                    <div style="display: flex;flex-direction: row;">
                        <div class="notifier-img-container">
                            <a href="/user/{{f.username}}">
                                <img src="{{f.profile.profile_pic.url}}" class="notifier-img"
                                    style="object-fit: cover;background-position: center;border-radius: 50%;" alt="...">
                            </a>
                        </div>
                        <div class="message" style="display: flex;flex-direction: column;word-break: break-all;">
                            <a href="/user/{{f.username}}">
                                <strong>{{f.username}}</strong>
                            </a>
                            <small class="text-muted mr-2" style="font-size:0.8rem">
                                {{f.user.profile.name}}
                            </small>
                        </div>
                    </div>
                    <button class="followbtn" data-userid="{{f.id}}">Follow</button>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No users in this list
        {% endif %}
    </div>
</div>
<script>

var csrfToken = $("input[name=csrfmiddlewaretoken]").val();

$('.followbtn').click(function(e){
    e.preventDefault();
    userid = $(this).data('userid')
    var unfollowbtn=$(this)
    $.ajax({
        url:'/follow/'+userid,
        data:{
            csrfmiddlewaretoken : csrfToken,
        },
        method:'POST',
        success:function(response){
            unfollowbtn.text('Following')
        }
    })
})
</script>
{% endblock %}

templates/app/following.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/home2.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile2.css' %}">


<style>
    .following-container {
        width: 100vmin;
        min-height: 100vh;
        display: flex;
        justify-content: center;
        padding-left: 5%;
        padding-right: 5%;
        padding-top: 5vmin;
    }

    .outer-container {
        width: 100%;
        min-height: 100vh;
        display: flex;
        justify-content: center;
        background-color: rgb(238, 238, 238);
    }

    .followbtn {
        background-color: crimson;
        color: white;
        border: 0px;
        border-radius: 5px;
        width: fit-content;
        padding: 5px 10px 5px 10px;
        transition: 0.2s ease;
    }

    .followbtn:hover {
        background-color: rgb(173, 6, 39);
    }
</style>

<nav class="navbar navbar-expand-lg nav-color sticky" style="position: sticky;top: 0;z-index: 1;">
    <div class="container-fluid">
        <a class="navbar-brand" href="/user/{{user.username}}">
            <img class="home-self-img" src="{{user.profile.profile_pic.url}}">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-icons white" style="font-size: 40px;">list</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                        Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">
                        Profile</a>
                </li>
                <a class="nav-link active" aria-current="page" href="/notifications">
                    Notifications</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Requests
                    </a>
                    <ul class="dropdown-menu nav-color" aria-labelledby="navbarDropdown">
                        {% if follow_req_notifications %}
                        {% for n in follow_req_notifications %}
                        <li class="dropdown-item" style="background-color: black;">
                            <a href="/user/{{n.notifier.username}}">{{n.notifier.username}} requested to follow you</a>
                            <a href="/req_accept/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-light bg-light btn-sm">Accept</button></a>
                            <a href="/req_delete/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-danger btn-sm">Delete</button></a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li><a class="dropdown-item" href="#">No requests</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li>
                    <a class="nav-link active" aria-current="page" href="/post">
                        New Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
            </ul>
            <form class="d-flex" action="/home_search" method="POST">
                {% csrf_token %}
                {% for msg in messages %}
                <p style="color: white;">{{msg}}</p>
                {% endfor %}
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-light bg-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<nav class="nav-color nav-footer">
    <a href="/"><i class="bi bi-house-door house-icon"></i></a>
</nav>

<div class="outer-container">
    <div class="following-container">
        {% if following_list %}
        <ul class="list-group followcontainer" id="followinglist">
            {% for f in following_list %}
            <li class="list-group-item center li-body">
                <div class="toast-header notibody">
                    <div style="display: flex;flex-direction: row;">
                        <div class="notifier-img-container">
                            <a href="/user/{{f.user.username}}">
                                <img src="{{f.user.profile.profile_pic.url}}" class="notifier-img"
                                    style="object-fit: cover;background-position: center;border-radius: 50%;" alt="...">
                            </a>
                        </div>
                        <div class="message" style="display: flex;flex-direction: column;word-break: break-all;">
                            <a href="/user/{{f.user.username}}">
                                <strong>{{f.user.username}}</strong>
                            </a>
                            <small class="text-muted mr-2" style="font-size:0.8rem">
                                {{f.user.profile.name}}
                            </small>
                        </div>
                    </div>
                    <button class="followbtn" data-userid="{{f.user.id}}">Follow</button>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No users in this list
        {% endif %}
    </div>
</div>


<script>

var csrfToken = $("input[name=csrfmiddlewaretoken]").val();

$('.followbtn').click(function(e){
    e.preventDefault();
    userid = $(this).data('userid')
    var unfollowbtn=$(this)
    $.ajax({
        url:'/follow/'+userid,
        data:{
            csrfmiddlewaretoken : csrfToken,
        },
        method:'POST',
        success:function(response){
            unfollowbtn.text('Following')
        }
    })
})
</script>
{% endblock %}

templates/app/newpost.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <div class="container" style="margin-top: 40px;">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="content" class="form-label"><h3><b>What's on your mind?</b></bWhat></h3></label>
                <textarea class="form-control" id="content" name="content" rows="10"></textarea>
            </div>
            <input type="submit" class="btn btn-primary btn-lg" value="Post">
        </form>
    </div>
{% endblock %}

templates/app/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">



<style>

</style>
<nav class="navbar navbar-expand-lg nav-color sticky" style="position: sticky;top: 0;z-index: 1;">
    <div class="container-fluid">
        <a class="navbar-brand" href="/user/{{user.username}}">
            <img class="home-self-img" src="{{user.profile.profile_pic.url}}">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-icons white" style="font-size: 40px;">list</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                        Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">
                        <b>Profile</b></a>
                </li>
                <a class="nav-link active" aria-current="page" href="/notifications">
                    Notifications</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Requests
                    </a>
                    <ul class="dropdown-menu nav-color" aria-labelledby="navbarDropdown">
                        {% if follow_req_notifications %}
                        {% for n in follow_req_notifications %}
                        <li class="dropdown-item" style="background-color: black;">
                            <a href="/user/{{n.notifier.username}}">{{n.notifier.username}} requested to follow you</a>
                            <a href="/req_accept/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-light bg-light btn-sm">Accept</button></a>
                            <a href="/req_delete/{{n.notifier.id}}?path={{request.path}}"><button
                                    class="btn btn-danger btn-sm">Delete</button></a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li><a class="dropdown-item" href="#">No requests</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li>
                    <a class="nav-link active" aria-current="page" href="/post">
                        New Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
            </ul>
            <form class="d-flex" action="/home_search" method="POST">
                {% csrf_token %}
                {% for msg in messages %}
                <p style="color: white;">{{msg}}</p>
                {% endfor %}
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-light bg-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<nav class="nav-color nav-footer">
    <a href="/"><i class="bi bi-house-door house-icon"></i></a>
</nav>

<div class="outermost-container">
    
    <div class="profile-container">

        <form method='POST' action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="line-first">
                <div class="profilepic-container">
                    <img src="{{user.profile.profile_pic.url}}" alt="" id="profilepic" class="profilepic">
                </div>
                <div class="profile-form-input">
                    {{form.profile_pic|add_class:'form-control profile-form'}}
                </div>
                <div class="details">
                    <input type="text" class="dummy" id="dummyage" placeholder="Age" value="{{user.profile.age}}">
                    <br>
                    <input type="text" class="dummy" id="dummyname" placeholder="Name" value="{{user.profile.name}}">
                    <br>
                    <input type="text" class="dummy" id="dummybio" placeholder="Bio" value="{{user.profile.bio}}">
                </div>
                {{form.age|add_class:'form-control my-form'}}
                {{form.name|add_class:'form-control my-form'}}
                {{form.bio|add_class:'form-control my-form'}}
        
    </div>
    <div class="line-second">
        <button class="profile-btn" type="submit">Save</button>
    </div>
</form>
    <div class="line-third">
        <span id="followers" class="selected">Followers ({{followerscount}})</span>
        <span id="following">Following ({{followingcount}})</span>
    </div>
    <div class="line-fourth">
        <ul class="list-group followcontainer" id="followerslist">
            {% for f in followerslist %}
            <li class="list-group-item center li-body">
                <div class="toast-header notibody">
                    <div style="display: flex;flex-direction: row;">
                        <div class="notifier-img-container">
                            <a href="/user/{{f.username}}">
                                <img src="{{f.profile.profile_pic.url}}" class="notifier-img"
                                    style="object-fit: cover;background-position: center;border-radius: 50%;" alt="...">
                            </a>
                        </div>
                        <div class="message" style="display: flex;flex-direction: column;word-break: break-all;">
                            <a href="/user/{{f.username}}">
                                <strong>{{f.username}}</strong>
                            </a>
                            <small class="text-muted mr-2" style="font-size:0.8rem">name</small>
                        </div>
                    </div>
                    <button class="removebtn" data-userid="{{f.id}}">Remove</button>
                </div>
            </li>
            {% endfor %}
        </ul>
        
        <ul class="list-group followcontainer" id="followinglist" style="display: none;">
            {% for f in followinglist %}
            <li class="list-group-item center li-body">
                <div class="toast-header notibody">
                    <div style="display: flex;flex-direction: row;">
                        <div class="notifier-img-container">
                            <a href="/user/{{f.user.username}}">
                                <img src="{{f.user.profile.profile_pic.url}}" class="notifier-img"
                                    style="object-fit: cover;background-position: center;border-radius: 50%;" alt="...">
                            </a>
                        </div>
                        <div class="message" style="display: flex;flex-direction: column;word-break: break-all;">
                            <a href="/user/{{f.user.username}}">
                                <strong>{{f.user.username}}</strong>
                            </a>
                            <small class="text-muted mr-2" style="font-size:0.8rem">name</small>
                        </div>
                    </div>
                    <button class="unfollowbtn" data-userid="{{f.user.id}}">Unfollow</button>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>


</div>
</div>


<script>
    $('.profilepic').click(function () {
        $('.profile-form').click()
    })
    document.getElementById('dummyage').addEventListener('change', function () {
        var age = this.value
        document.getElementById('id_age').value = age;
    })
    document.getElementById('dummyname').addEventListener('change', function () {
        var name = this.value
        document.getElementById('id_name').value = name;
    })
    document.getElementById('dummybio').addEventListener('change', function () {
        var bio = this.value
        document.getElementById('id_bio').value = bio;
    })

    var dp = document.querySelector('#profilepic')
    var img_selected_form = document.querySelector('#id_profile_pic')
    img_selected_form.addEventListener('change', function () {
        const file = this.files[0]
        if (file) {
            const reader = new FileReader(file);
            reader.addEventListener('load', function () {
                dp.setAttribute('src', this.result)
            })
            reader.readAsDataURL(file)
        }
    })
</script>

<script type="text/javascript" src="/static/js/profile.js"></script>

{% endblock %}